### ISSUE TITLE
Weird error after initial setup

### ISSUE THREAD

**Issue by craig-dae** [component-driven/cypress-axe#82]
cy.readFile() must be passed a non-empty string as its 1st argument. You passed: 146.Learn more

This happens after finishing setup and trying to run a sample test. 

This is in my command that I use to login:
```js
    .then((url) => {
      cy.intercept('api/users/user/profile/').as('login');
      cy.visit(url);
      cy.wait('@login');
      cy.injectAxe();
    }),
```

Error happens on the `cy.injectAxe()` line. 

Thanks!

**Comment by craig-dae** [comment]
This is what the relevant section of code is transpiling to. Note that, this time around, it's 144 instead of 146. 

```js
exports.configureAxe = exports.injectAxe = void 0;
exports.injectAxe = function () {
    cy.readFile(/*require.resolve*/(144)).then(function (source) {
        return cy.window({ log: false }).then(function (window) {
            window.eval(source);
        });
    });
};
```

**Comment by craig-dae** [comment]
I see other similar errors dating back to last year. I've tried several of the fixes with no luck. I think we're going to move away from using axe at this point, and try another tool.

**Comment by craig-dae** [comment]
Tried rolling back to version `0.9.1`, which seemed to be the last version people used before they started getting errors, and I get `exports is not defined`.

I'm going to leave this branch open and move away from axe. If you guys can help, that'd be great. If not, we will not be able to use axe. Thanks

**Comment by Sadorus** [comment]
@craig-dae Did you fix the issue? I have the same problem and any workarounds don't work for me.

**Comment by sshaar08** [comment]
@Sadorus  and @craig-dae i had the same issue my solve was to pin "axe-core": "4.0.2", and "cypress-axe": "0.9.1",

then I was able to get the violations

**Comment by bstruthers** [comment]
I was able to work around this by creating my own `injectAxe` method in my tests.

```
const injectAxe = () => {
  //cy.injectAxe();
  // cy.injectAxe is currently broken. https://github.com/component-driven/cypress-axe/issues/82

  // Creating our own injection logic
  cy.readFile('../../node_modules/axe-core/axe.min.js').then((source) => {
    return cy.window({ log: false }).then((window) => {
        window.eval(source);
    });
  });
};
```
Then instead of calling `cy.injectAxe()`, I call my own method to inject the script.

**Comment by sshaar08** [comment]
i submitted a pr here: https://github.com/component-driven/cypress-axe/pull/86 this should fix it similarly to other plugins with the same issue. seems to be a typescript issue

**Comment by JessicaSachs** [comment]
There's an issue with this. It crashes if `require` is undefined... Which happens if the webpack config doesn't transpile node-modules.

**Comment by James-Vanguard** [comment]
I am still getting this error on version 0.12.2

**Comment by sshaar08** [comment]
can you edit to this commit to see if it solves your issue: https://github.com/component-driven/cypress-axe/pull/86/commits/3dac12c160f07f827180e949ae248321d6d0e161 I changed the second check, but may solve your issue

**Comment by caraclarke** [comment]
I am also still getting this on v0.13.0, axe v4.3.3 and cypress v5.6.0

**Comment by guilhermenasszup** [comment]
I'm calling injectAxe inside beforeEach hook, but I'm still getting this error:

cy.readFile() must be passed a non-empty string as its 1st argument. You passed: 190.

Because this error occurred during a before each hook we are skipping the remaining tests in the current suite: Home integration tests

Inside node_modules folder, I checked the index.js and the error occurs here:
![image](https://user-images.githubusercontent.com/64160860/135083969-ebb09662-31d8-4a0e-aef6-bb10dc17ff55.png)

**Comment by DannyvanHolten** [comment]
This issue is not resolved when using cypress-axe 0.13.0 and axe-core 4.3.5

When I'm seeing this I'm even wondering if this is still being maintained?

**Comment by soniajains** [comment]
Yes, this issue still exists with the latest version, we tried calling our own method to inject the script.

 const injectAxe = () => {

  cy.readFile('../../node_modules/axe-core/axe.min.js').then((source) => {
    return cy.window({ log: false }).then((window) => {
        window.eval(source);
    });
  });
};

**Comment by moizang** [comment]
Similar issue encountered today using cypress-axe 0.13.0, this issue should probably be re-opened

**Comment by leads** [comment]
> I was able to work around this by creating my own `injectAxe` method in my tests.
> 
> ```
> const injectAxe = () => {
>   //cy.injectAxe();
>   // cy.injectAxe is currently broken. https://github.com/component-driven/cypress-axe/issues/82
> 
>   // Creating our own injection logic
>   cy.readFile('../../node_modules/axe-core/axe.min.js').then((source) => {
>     return cy.window({ log: false }).then((window) => {
>         window.eval(source);
>     });
>   });
> };
> ```
> 
> Then instead of calling `cy.injectAxe()`, I call my own method to inject the script.

Two years later and I've just implemented this and it's fixed the issue. Using cypress ina nx setup, versions are:

`"axe-core": "^4.6.3",
    "cypress-axe": "^1.3.0",`

**Comment by B34v0n** [comment]
I just had the same issue, but i was able to fix it with defining the axe-core in injectAxe, like it was told in the README:
https://www.npmjs.com/package/cypress-axe#cyinjectaxe

`cy.injectAxe({ axeCorePath: 'node_modules/axe-core/axe.min.js' });` instead if `cy.injectAxe()`.
Hope that helps someone. :)
